ALTER TABLE expenses ADD COLUMN IF NOT EXISTS recurring BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS recurringInterval VARCHAR(20);
ALTER TABLE expenses ADD COLUMN IF NOT EXISTS nextRecurringDate DATE;
ALTER TABLE incomes ADD COLUMN IF NOT EXISTS recurring BOOLEAN DEFAULT FALSE NOT NULL;
ALTER TABLE incomes ADD COLUMN IF NOT EXISTS recurringInterval VARCHAR(20);
ALTER TABLE incomes ADD COLUMN IF NOT EXISTS nextRecurringDate DATE;
