export const ENV = {
  get appId() { return process.env.VITE_APP_ID ?? ""; },
  get cookieSecret() { return process.env.JWT_SECRET ?? ""; },
  get databaseUrl() { return process.env.DATABASE_URL ?? ""; },
  get oAuthServerUrl() { return process.env.OAUTH_SERVER_URL ?? ""; },
  get ownerOpenId() { return process.env.OWNER_OPEN_ID ?? ""; },
  get isProduction() { return process.env.NODE_ENV === "production"; },
  get forgeApiUrl() { return process.env.BUILT_IN_FORGE_API_URL ?? ""; },
  get forgeApiKey() { return process.env.BUILT_IN_FORGE_API_KEY ?? ""; },
  get pixKey() { return process.env.PIX_KEY ?? ""; },
  get openpixAppId() { return process.env.OPENPIX_APP_ID ?? ""; },
  get appUrl() { return process.env.APP_URL ?? "http://localhost:3000"; },
  get whatsappPhone() { return process.env.WHATSAPP_PHONE ?? ""; },
  get whatsappApiKey() { return process.env.WHATSAPP_API_KEY ?? ""; },
  get resendApiKey() { return process.env.RESEND_API_KEY ?? ""; },
};
